name: Static Website CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies (if any)
        run: echo "No dependencies for static site"

      - name: Build Site
        run: |
          mkdir -p dist
          echo "<h1>My Static Site</h1>" > dist/index.html

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Tests
        run: |
          test -f dist/index.html && echo "Test Passed" || exit 1

  docker-build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t static-site:latest .

  docker-tag:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Tag Docker Image
        run: docker tag static-site:latest your-dockerhub-username/static-site:latest

  docker-push:
    runs-on: ubuntu-latest
    needs: docker-tag
    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Image
        run: docker push your-dockerhub-username/static-site:latest
