name: Static Website CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.vars.outputs.short_sha }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Generate Static Website
        run: |
          mkdir -p dist
          echo "<h1>My Static Site</h1>" > dist/index.html

      - name: Upload dist as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Set Git SHA as output
        id: vars
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Test if index.html exists
        run: |
          test -f dist/index.html && echo "Test passed!" || (echo "Test failed!" && exit 1)

  docker-build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Build Docker image
        run: docker build -t static-site:build .

      - name: Save Docker image as artifact
        run: docker save static-site:build -o static-site.tar

      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: static-site.tar

  docker-tag:
    runs-on: ubuntu-latest
    needs: [docker-build, build]
    outputs:
      image_tag: ${{ steps.vars.outputs.image_tag }}
    steps:
      - name: Download Docker image
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: .

      - name: Load Docker image
        run: docker load -i static-site.tar

      - name: Tag Docker images (latest and SHA)
        id: vars
        run: |
          short_sha="${{ needs.build.outputs.short_sha }}"
          docker tag static-site:build your-dockerhub-username/static-site:latest
          docker tag static-site:build your-dockerhub-username/static-site:$short_sha
          echo "image_tag=$short_sha" >> $GITHUB_OUTPUT

      - name: Save tagged images
        run: |
          docker save your-dockerhub-username/static-site:latest -o tagged-latest.tar
          docker save your-dockerhub-username/static-site:${{ needs.build.outputs.short_sha }} -o tagged-sha.tar

      - name: Upload tagged latest
        uses: actions/upload-artifact@v4
        with:
          name: tagged-latest
          path: tagged-latest.tar

      - name: Upload tagged sha
        uses: actions/upload-artifact@v4
        with:
          name: tagged-sha
          path: tagged-sha.tar

  docker-push:
    runs-on: ubuntu-latest
    needs: [docker-tag, build]
    steps:
      - name: Download tagged images
        uses: actions/download-artifact@v4
        with:
          name: tagged-latest
          path: .

      - name: Download tagged SHA image
        uses: actions/download-artifact@v4
        with:
          name: tagged-sha
          path: .

      - name: Load Docker images
        run: |
          docker load -i tagged-latest.tar
          docker load -i tagged-sha.tar

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker images (latest + SHA)
        run: |
          docker push your-dockerhub-username/static-site:latest
          docker push your-dockerhub-username/static-site:${{ needs.build.outputs.short_sha }}
